# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'
  version: 2.2.0

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build

- task: DotNetCoreCLI@2
  condition: succeeded()
  inputs:
    command: test
    projects: '**/*Test.csproj'

- task: NuGetCommand@2
  condition: succeeded()
  inputs: 
    command: pack
    versioningScheme: byEnvVar
    versionEnvVar: version

- task: PublishBuildArtifacts@1
  condition: succeeded()

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'IntelliTect-Nuget-Feed'
    versioningScheme: byEnvVar
    versionEnvVar: version